### PR TITLE
fix: store access tokens in memory instead of localStorage

### LINKED ISSUE #100: Console: don't store access token in the storage
Storing tokens in `localStorage` has security implications:

```
  logout: (): void => {
    localStorage.removeItem("polaris_access_token")
```

Because `localStorage` is readable by any JavaScript running on the page, an XSS vulnerability would allow an attacker to extract the access token.

Not a blocker for an internal/admin console, but we should at least track this as a follow-up improvement (e.g., memory-only tokens).

### PR DESCRIPTION
**Pull request by developerzohaib786**
- Replaced localStorage token storage with in-memory storage in ApiClient
- Removed token persistence check from useAuth hook
- Updated logout to use centralized clearAccessToken method
- Tokens are now cleared automatically when browser tab closes
- Prevents XSS attacks from extracting access tokens
- Realm configuration remains in localStorage (non-sensitive)

Fixes #100

### CODE REVIEW

**Comment by dimas-b** [comment]
@binarycat0: could you review, please?

File: apprunner/maven-plugin/src/test/resources-its/org/apache/polaris/apprunner/maven/ITPolarisMavenPlugin/applicationIdSpecified/src/test/java/org/apache/polaris/appruner/maven/mavenit/ITSimulatingTestUsingThePlugin.java [hunk 1]
```diff
@@ -1,48 +0,0 @@
...
-
-import org.junit.jupiter.api.Test;
-import org.projectnessie.client.api.NessieApiV1;
-import org.projectnessie.client.http.HttpClientBuilder;
-import org.projectnessie.model.Branch;
-
-/**
- * This is not a test for the plugin itself, this is a test that is run BY the test for the plugin.
- */
-class ITSimulatingTestUsingThePlugin {
```
Comment (dimas-b) [inline apprunner/maven-plugin/src/test/resources-its/org/apache/polaris/apprunner/maven/ITPolarisMavenPlugin/applicationIdSpecified/src/test/java/org/apache/polaris/appruner/maven/mavenit/ITSimulatingTestUsingThePlugin.java]: why remove this class?

File: benchmarks/gradlew
Comment (dimas-b) [inline benchmarks/gradlew]: Please avoid changing file unrelated to the purpose of the PR

File: console/src/api/auth.ts [hunk 2]
```diff
@@ -43,7 +43,7 @@ export const authApi = {
     formData.append("grant_type", "client_credentials")
     formData.append("client_id", clientId)
     formData.append("client_secret", clientSecret)
-    formData.append("scope", "PRINCIPAL_ROLE:ALL")
+    formData.append("scope", "PRINCIPAL_ROLE: ALL")
```
Comment (dimas-b) [inline console/src/api/auth.ts]: This change make the value invalid, AFAIK

**Comment by developerzohaib786** [comment]
@dimas-b please Have a look now. sorry i did not aware of rule of opening another pr so i opened pull # 115. please have a look on the commited changes. thank u!

File: console/src/api/auth.ts [hunk 3]
```diff
@@ -98,9 +98,9 @@ export const authApi = {
 
   refreshToken: async (accessToken: string): Promise<OAuthTokenResponse> => {
     const formData = new URLSearchParams()
-    formData.append("grant_type", "urn:ietf:params:oauth:grant-type:token-exchange")
+    formData.append("grant_type", "urn:ietf:params: oauth:grant-type:token-exchange")
     formData.append("subject_token", accessToken)
-    formData.append("subject_token_type", "urn:ietf:params:oauth:token-type:access_token")
+    formData.append("subject_token_type", "urn: ietf:params:oauth: token-type:access_token")
```
Comment (dimas-b) [inline console/src/api/auth.ts]: Adding spaces makes these values invalid.

**Review by dimas-b — COMMENTED** [review]
Thanks for your contribution, @developerzohaib786 !

Please see my general comments below.

I'm not familiar with the UI framework used here, so I'll have to rely on someone else to review the material code changes in this PR.

File: console/src/hooks/useAuth.tsx [hunk 4]
```diff
@@ -77,5 +68,4 @@ export function useAuth() {
     throw new Error("useAuth must be used within an AuthProvider")
   }
   return context
-}
-
+}
```
Comment (binarycat0) [inline console/src/hooks/useAuth.tsx]: NIT: Let’s avoid extra whitespace-only changes and keep this PR focused on functional updates.

**Review by binarycat0 — CHANGES_REQUESTED** [review]
Thanks for the PR! 👍 I’ve left a few comments, please take a look when you can. 

I’ll also test it locally later.

**Comment by binarycat0** [comment]
@developerzohaib786 thanks for handling this. 
Resolving conflicts is on the author of the PR. Please rebase your branch on the `main`.

**Comment by developerzohaib786** [comment]
I have encountered an error while commiting the change of removing whitespaces. Unwanted files has been staged and pushed let me fix it quicky again!!

**Comment by binarycat0** [comment]
@developerzohaib786 Hello. I apologize for the inconvenience, but you need to rebase on `main` again, because we delivered requested changes for including `package-lock.json` to `.gitignore` file.

**Review by binarycat0 — APPROVED** [review]
Tested locally. Works well for me.
